### ISSUE TITLE
Use this without react-navigation?

### ISSUE THREAD

**Issue by namnm** [gaoxiaosong/react-native-general-actionsheet#4]
Right now we need to add and config react-navigation to make it work? Can we use this package without react-navigation?

**Comment by gaoxiaosong** [comment]
@namnm Yes. It does not depend on `react-navigation`. Only show a modal view with `react-native-root-siblings` which uses api of `AppRegistry`.

**Comment by namnm** [comment]
Ok, when I install it, npm log says that there's a peer dependency of react-navigation@*
I installed react-navigation@latest but it didnt work because react-navigation v3 require container setup.
So I remove that version and install v2 instead, then it work without any setup.

I think you should update the dependency version in the react-native-pure-navigation-bar package.

**Comment by gaoxiaosong** [comment]
@namnm I only use `getSafeAreaInset` api in it and will replace it with `SafeAreaView` later. Thanks for reporting it~
